FROM m0elnx/ubuntu-32bit
MAINTAINER Anil Altinay <aaltinay@uci.edu>

# S2E build dependencies
RUN echo "deb-src http://archive.ubuntu.com/ubuntu trusty main" >> /etc/apt/sources.list
RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ trusty-updates main" >> /etc/apt/sources.list
RUN echo "deb-src http://security.ubuntu.com/ubuntu trusty-security main" >> /etc/apt/sources.list
RUN apt-get update \
    && apt-get build-dep -y llvm-3.3 qemu \    
    && apt-get install -y build-essential subversion git gettext liblua5.1-0-dev \
    libsdl1.2-dev libsigc++-2.0-dev binutils-dev python-docutils \
    python-pygments nasm libiberty-dev libc6-dev wget \
    && apt-get install -y gdb vim \
    && apt-get install -y g++-multilib graphviz kpartx mingw32 cmake3 realpath \
    time sudo libgettextpo-dev

# Fix locale
RUN locale-gen en_US.UTF-8

# Expose VNC server port
EXPOSE 5900
